from typing import List, Literal, Dict
from .flow import Flow

class Exporter:
    def export(self, flow: Flow, shell: Literal["bash", "zsh"] = "bash", preset: str = "local", variables: Dict[str, str] = None) -> str:
        lines = []
        
        # Shebang
        if shell == "zsh":
            lines.append("#!/bin/zsh")
        else:
            lines.append("#!/bin/bash")
            
        lines.append("")
        lines.append("# Generated by FlowShotCLI")
        lines.append("# https://github.com/example/flowshot")
        lines.append("")
        
        # Presets & Safety
        if preset == "ci":
             lines.append("# Preset: CI (Non-interactive)")
             lines.append("set -euo pipefail")
             # CI might want xtrace
             lines.append("set -x")
        elif preset == "safe":
             lines.append("# Preset: Safe (Interactive confirm)")
             lines.append("set -euo pipefail")
        else: # local
             lines.append("# Preset: Local")
             lines.append("set -euo pipefail")
             
        lines.append("")
        
        # Variables
        if variables:
            lines.append("# --- Variables ---")
            for name, val in variables.items():
                lines.append(f"{name}={val}")
            lines.append("")
            
        # Flow content
        lines.append(f"# Flow: {flow.name}")
        lines.append("")
        
        # Helper for confirmation if safe mode
        if preset == "safe":
            lines.append("confirm() {")
            lines.append('  read -p "Run: $1? [y/N] " -n 1 -r')
            lines.append('  echo')
            lines.append('  if [[ ! $REPLY =~ ^[Yy]$ ]]; then return 1; fi')
            lines.append("}")
            lines.append("")
        
        for idx, cmd in enumerate(flow.commands):
            if cmd.type == "step":
                lines.append("")
                lines.append(f"# --- {cmd.cmd} ---")
                lines.append("")
                continue

            if cmd.note:
                lines.append(f"# Note: {cmd.note}")
            
            final_cmd = cmd.cmd
            # Replace variables if any matches
            if variables:
                for name, val in variables.items():
                   if val in final_cmd:
                       final_cmd = final_cmd.replace(val, f"${{{name}}}")
            
            if preset == "safe":
                 lines.append(f"confirm '{final_cmd}' && {final_cmd}")
            else:
                 lines.append(final_cmd)
            
        lines.append("")
        return "\n".join(lines)
